package main

import (
	"fmt"

	"github.com/daniacca/achemdb/internal/achem"
)

func main() {
	schema := achem.NewSchema("security-alerts").WithSpecies(
		achem.Species{
			Name:        "Event",
			Description: "Raw security/ops events",
		},
		achem.Species{
			Name:        "Suspicion",
			Description: "Suspicious entities (IP/user/etc.)",
		},
		achem.Species{
			Name:        "Alert",
			Description: "Alerts generated by the system",
		},
	).WithReactions(
		NewLoginFailureToSuspicionReaction(),
		NewSuspicionToAlertReaction(),
		NewDecayReaction(),
	)

	env := achem.NewEnvironment(schema)

	// Un po' di eventi falliti dallo stesso IP
	for i := 0; i < 5; i++ {
		env.Insert(achem.NewMolecule("Event", map[string]any{
			"type": "login_failed",
			"ip":   "1.2.3.4",
		}, 0))
	}

	for range 100 {
		env.Step()
	}

	var events, suspicions, alerts int
	for _, m := range env.AllMolecules() {
		switch m.Species {
		case "Event":
			events++
		case "Suspicion":
			suspicions++
		case "Alert":
			alerts++
		}
	}

	fmt.Println("Events:", events)
	fmt.Println("Suspicions:", suspicions)
	fmt.Println("Alerts:", alerts)
}
